root: true

parser: '@typescript-eslint/parser'

parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  browser: true
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - next/core-web-vitals
  - prettier

plugins:
  - '@typescript-eslint'
  - react
  - react-hooks
  - jsx-a11y
  - import # eslint-plugin-import 사용

rules:
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-empty-object-type': off
  'no-empty-pattern': off
  react/react-in-jsx-scope: off
  react/prop-types: off

  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      pathGroups:
        - pattern: react
          group: external
          position: before
        - pattern: '@/**'
          group: internal
          position: after
      pathGroupsExcludedImportTypes:
        - react
      alphabetize:
        order: asc
        caseInsensitive: true

settings:
  react:
    version: detect
