singleQuote: true
semi: false
useTabs: false
tabWidth: 2
trailingComma: 'all'
printWidth: 100
plugins:
  - prettier-plugin-multiline-arrays
multilineArraysWrapThreshold: 2
overrides:
  - files: '*.scss'
    options:
      singleQuote: true
      trailingComma: 'none'
      printWidth: 80
      parser: 'scss'
